[tool.poetry]
name = "mephisto"
version = "0.1.0"
description = ""
authors = ["Jack Urbanek <jju@fb.com>"]

[tool.poetry.dependencies]
python = "^3.6"
click = "^7.0"
flask = "^1.1"
click_default_group = "^1.2"
boto3 = "^1.10"
requests = "^2.22"
sh = "^1.12"
websocket-client = "^0.56.0"
recordclass = "^0.12.0"
argparse = "=1.1"
tornado = "^6.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
pylint = "^2.4"
mypy = "^0.761.0"

[tool.poetry.scripts]
'mephisto' = 'mephisto.client.cli:cli'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[mypy]
ignore_missing_imports = true
