name: version-sync

on:
  pull_request:
  push:
    branches: [main]

jobs:
  check-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Run version sync script
        run: python scripts/sync_mephisto_task.py check
